#!/usr/bin/env -S node
import type { Contract as End } from '../../snapshots/f50fb5acc2eb030d32c09f383019c1e577e1a57d6ddb1b97cf74f0cdbfae90bd/contract';
import endContract from '../../snapshots/f50fb5acc2eb030d32c09f383019c1e577e1a57d6ddb1b97cf74f0cdbfae90bd/contract.json' with { type: 'json' };
import { Migration, MigrationCLI, col, fn, lit, primaryKey } from '@prisma/orm-postgres/migration';

export default class M extends Migration<never, End> {
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.createSchema({ schema: 'public' }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'AuditAction',
        members: [
          'CREATE',
          'UPDATE',
          'DELETE',
          'RESTORE',
          'JOIN',
          'LEAVE',
          'SETTLE',
          'INVITE',
          'REVOKE',
        ],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'EventType',
        members: [
          'GROUP_CREATED',
          'GROUP_UPDATED',
          'GROUP_ARCHIVED',
          'MEMBER_JOINED',
          'MEMBER_LEFT',
          'MEMBER_ROLE_CHANGED',
          'INVITE_CREATED',
          'INVITE_REVOKED',
          'EXPENSE_ADDED',
          'EXPENSE_UPDATED',
          'EXPENSE_DELETED',
          'COMMENT_ADDED',
          'SETTLEMENT_RECORDED',
          'SETTLEMENT_DELETED',
          'RECURRING_CREATED',
          'RECURRING_UPDATED',
          'RECURRING_GENERATED',
          'PAYMENT_REMINDER',
        ],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'GroupType',
        members: ['HOME', 'TRIP', 'COUPLE', 'EVENT', 'PROJECT', 'OTHER'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'MemberRole',
        members: ['OWNER', 'ADMIN', 'MEMBER'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'RecurrenceFreq',
        members: ['DAILY', 'WEEKLY', 'FORTNIGHTLY', 'MONTHLY', 'QUARTERLY', 'YEARLY'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'SettlementMethod',
        members: ['CASH', 'UPI', 'BANK_TRANSFER', 'CARD', 'OTHER'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'SplitMethod',
        members: ['EQUAL', 'EXACT', 'PERCENT', 'SHARES', 'ITEMISED'],
      }),
      this.createTable({
        schema: 'public',
        table: 'Activity',
        columns: [
          col('actorId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('data', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('entityId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('entityType', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('groupId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('summary', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('type', '"EventType"', {
            notNull: true,
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'EventType' } },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'Activity_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'AuditLog',
        columns: [
          col('action', '"AuditAction"', {
            notNull: true,
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'AuditAction' } },
          }),
          col('actorClerkId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('actorUserId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('after', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('before', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('diff', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('entityId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('entityType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('groupId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('ip', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('requestId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('route', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('traceId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userAgent', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'AuditLog_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'Category',
        columns: [
          col('color', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('emoji', 'text', {
            notNull: true,
            default: lit('🏷️'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('groupId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('key', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('label', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('sortOrder', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'Category_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'Comment',
        columns: [
          col('body', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('deletedAt', 'timestamp(3)', {
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('expenseId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'Comment_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'Expense',
        columns: [
          col('amountMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('categoryId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('createdById', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('currency', 'text', {
            notNull: true,
            default: lit('INR'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('date', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('deletedAt', 'timestamp(3)', {
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('description', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('exchangeRate', 'numeric(18,8)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 18, scale: 8 } },
          }),
          col('groupAmountMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('groupId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('receiptUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('recurringExpenseId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('splitMethod', '"SplitMethod"', {
            notNull: true,
            default: lit('EQUAL'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'SplitMethod' } },
          }),
          col('updatedAt', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'Expense_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'ExpensePayer',
        columns: [
          col('amountMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('expenseId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('groupAmountMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'ExpensePayer_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'ExpenseSplit',
        columns: [
          col('amountMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('expenseId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('groupAmountMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('percentBp', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('weight', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'ExpenseSplit_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'Group',
        columns: [
          col('archivedAt', 'timestamp(3)', {
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('colorKey', 'text', {
            notNull: true,
            default: lit('ink'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('createdById', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('currency', 'text', {
            notNull: true,
            default: lit('INR'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('deletedAt', 'timestamp(3)', {
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('emoji', 'text', {
            notNull: true,
            default: lit('🧾'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('simplifyDebts', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('type', '"GroupType"', {
            notNull: true,
            default: lit('OTHER'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'GroupType' } },
          }),
          col('updatedAt', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'Group_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'GroupMember',
        columns: [
          col('groupId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('joinedAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('leftAt', 'timestamp(3)', {
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('nickname', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('role', '"MemberRole"', {
            notNull: true,
            default: lit('MEMBER'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'MemberRole' } },
          }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'GroupMember_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'InviteCode',
        columns: [
          col('code', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('createdById', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('expiresAt', 'timestamp(3)', {
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('groupId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('maxUses', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('revokedAt', 'timestamp(3)', {
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('token', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('useCount', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'InviteCode_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'Notification',
        columns: [
          col('body', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('data', 'jsonb', { codecRef: { codecId: 'pg/jsonb@1' } }),
          col('entityId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('entityType', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('groupId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('href', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('readAt', 'timestamp(3)', {
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('type', '"EventType"', {
            notNull: true,
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'EventType' } },
          }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'Notification_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'PushSubscription',
        columns: [
          col('auth', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('endpoint', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('failureCount', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('lastSeenAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('p256dh', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userAgent', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'PushSubscription_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'RecurringExpense',
        columns: [
          col('amountMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('anchorDay', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('categoryId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('createdById', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('currency', 'text', {
            notNull: true,
            default: lit('INR'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('deletedAt', 'timestamp(3)', {
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('description', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('endDate', 'timestamp(3)', {
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('frequency', '"RecurrenceFreq"', {
            notNull: true,
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'RecurrenceFreq' } },
          }),
          col('groupId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('interval', 'int4', {
            notNull: true,
            default: lit(1),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('isPaused', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('lastRunAt', 'timestamp(3)', {
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('nextRunAt', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('payerConfig', 'jsonb', { notNull: true, codecRef: { codecId: 'pg/jsonb@1' } }),
          col('splitConfig', 'jsonb', { notNull: true, codecRef: { codecId: 'pg/jsonb@1' } }),
          col('splitMethod', '"SplitMethod"', {
            notNull: true,
            default: lit('EQUAL'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'SplitMethod' } },
          }),
          col('startDate', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('updatedAt', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('weekday', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'RecurringExpense_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'RecurringRun',
        columns: [
          col('error', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('expenseId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('ranAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('recurringExpenseId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('scheduledFor', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'RecurringRun_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'Settlement',
        columns: [
          col('amountMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('createdById', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('currency', 'text', {
            notNull: true,
            default: lit('INR'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('date', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('deletedAt', 'timestamp(3)', {
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('exchangeRate', 'numeric(18,8)', {
            notNull: true,
            codecRef: { codecId: 'pg/numeric@1', typeParams: { precision: 18, scale: 8 } },
          }),
          col('fromUserId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('groupAmountMinor', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('groupId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('method', '"SettlementMethod"', {
            notNull: true,
            default: lit('UPI'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'SettlementMethod' } },
          }),
          col('note', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('toUserId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'Settlement_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'User',
        columns: [
          col('clerkId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamp(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('defaultCurrency', 'text', {
            notNull: true,
            default: lit('INR'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('deletedAt', 'timestamp(3)', {
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('imageUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('locale', 'text', {
            notNull: true,
            default: lit('en-IN'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('name', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('pushEnabled', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('remindersEnabled', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('timezone', 'text', {
            notNull: true,
            default: lit('Asia/Kolkata'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamp(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamp-string@1', typeParams: { precision: 3 } },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'User_pkey' })],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Activity',
        index: 'Activity_actorId_createdAt_idx',
        columns: ['actorId', 'createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Activity',
        index: 'Activity_groupId_createdAt_idx',
        columns: ['groupId', 'createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'AuditLog',
        index: 'AuditLog_actorUserId_createdAt_idx',
        columns: ['actorUserId', 'createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'AuditLog',
        index: 'AuditLog_entityType_entityId_idx',
        columns: ['entityType', 'entityId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'AuditLog',
        index: 'AuditLog_groupId_createdAt_idx',
        columns: ['groupId', 'createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'AuditLog',
        index: 'AuditLog_traceId_idx',
        columns: ['traceId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Category',
        index: 'Category_groupId_idx',
        columns: ['groupId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Category',
        index: 'Category_groupId_key_key',
        columns: ['groupId', 'key'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'Comment',
        index: 'Comment_expenseId_createdAt_idx',
        columns: ['expenseId', 'createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Expense',
        index: 'Expense_createdById_idx',
        columns: ['createdById'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Expense',
        index: 'Expense_groupId_deletedAt_date_idx',
        columns: ['groupId', 'deletedAt', 'date'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Expense',
        index: 'Expense_recurringExpenseId_idx',
        columns: ['recurringExpenseId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ExpensePayer',
        index: 'ExpensePayer_expenseId_userId_key',
        columns: ['expenseId', 'userId'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'ExpensePayer',
        index: 'ExpensePayer_userId_idx',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ExpenseSplit',
        index: 'ExpenseSplit_expenseId_userId_key',
        columns: ['expenseId', 'userId'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'ExpenseSplit',
        index: 'ExpenseSplit_userId_idx',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Group',
        index: 'Group_createdById_idx',
        columns: ['createdById'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Group',
        index: 'Group_deletedAt_idx',
        columns: ['deletedAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'GroupMember',
        index: 'GroupMember_groupId_leftAt_idx',
        columns: ['groupId', 'leftAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'GroupMember',
        index: 'GroupMember_groupId_userId_key',
        columns: ['groupId', 'userId'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'GroupMember',
        index: 'GroupMember_userId_leftAt_idx',
        columns: ['userId', 'leftAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'InviteCode',
        index: 'InviteCode_code_key',
        columns: ['code'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'InviteCode',
        index: 'InviteCode_groupId_revokedAt_idx',
        columns: ['groupId', 'revokedAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'InviteCode',
        index: 'InviteCode_token_key',
        columns: ['token'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'Notification',
        index: 'Notification_groupId_idx',
        columns: ['groupId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Notification',
        index: 'Notification_userId_createdAt_idx',
        columns: ['userId', 'createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Notification',
        index: 'Notification_userId_readAt_idx',
        columns: ['userId', 'readAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'PushSubscription',
        index: 'PushSubscription_endpoint_key',
        columns: ['endpoint'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'PushSubscription',
        index: 'PushSubscription_userId_idx',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'RecurringExpense',
        index: 'RecurringExpense_groupId_idx',
        columns: ['groupId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'RecurringExpense',
        index: 'RecurringExpense_isPaused_deletedAt_nextRunAt_idx',
        columns: ['isPaused', 'deletedAt', 'nextRunAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'RecurringRun',
        index: 'RecurringRun_recurringExpenseId_scheduledFor_key',
        columns: ['recurringExpenseId', 'scheduledFor'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'RecurringRun',
        index: 'RecurringRun_scheduledFor_idx',
        columns: ['scheduledFor'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Settlement',
        index: 'Settlement_fromUserId_idx',
        columns: ['fromUserId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Settlement',
        index: 'Settlement_groupId_deletedAt_date_idx',
        columns: ['groupId', 'deletedAt', 'date'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Settlement',
        index: 'Settlement_toUserId_idx',
        columns: ['toUserId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'User',
        index: 'User_clerkId_key',
        columns: ['clerkId'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'User',
        index: 'User_deletedAt_idx',
        columns: ['deletedAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'User',
        index: 'User_email_key',
        columns: ['email'],
        extras: { unique: true },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Activity',
        foreignKey: {
          name: 'Activity_actorId_fkey',
          columns: ['actorId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Activity',
        foreignKey: {
          name: 'Activity_groupId_fkey',
          columns: ['groupId'],
          references: { schema: 'public', table: 'Group', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'AuditLog',
        foreignKey: {
          name: 'AuditLog_actorUserId_fkey',
          columns: ['actorUserId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'setNull',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Category',
        foreignKey: {
          name: 'Category_groupId_fkey',
          columns: ['groupId'],
          references: { schema: 'public', table: 'Group', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Comment',
        foreignKey: {
          name: 'Comment_expenseId_fkey',
          columns: ['expenseId'],
          references: { schema: 'public', table: 'Expense', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Comment',
        foreignKey: {
          name: 'Comment_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Expense',
        foreignKey: {
          name: 'Expense_categoryId_fkey',
          columns: ['categoryId'],
          references: { schema: 'public', table: 'Category', columns: ['id'] },
          onDelete: 'setNull',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Expense',
        foreignKey: {
          name: 'Expense_createdById_fkey',
          columns: ['createdById'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'restrict',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Expense',
        foreignKey: {
          name: 'Expense_groupId_fkey',
          columns: ['groupId'],
          references: { schema: 'public', table: 'Group', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Expense',
        foreignKey: {
          name: 'Expense_recurringExpenseId_fkey',
          columns: ['recurringExpenseId'],
          references: { schema: 'public', table: 'RecurringExpense', columns: ['id'] },
          onDelete: 'setNull',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ExpensePayer',
        foreignKey: {
          name: 'ExpensePayer_expenseId_fkey',
          columns: ['expenseId'],
          references: { schema: 'public', table: 'Expense', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ExpensePayer',
        foreignKey: {
          name: 'ExpensePayer_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ExpenseSplit',
        foreignKey: {
          name: 'ExpenseSplit_expenseId_fkey',
          columns: ['expenseId'],
          references: { schema: 'public', table: 'Expense', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'ExpenseSplit',
        foreignKey: {
          name: 'ExpenseSplit_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Group',
        foreignKey: {
          name: 'Group_createdById_fkey',
          columns: ['createdById'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'restrict',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'GroupMember',
        foreignKey: {
          name: 'GroupMember_groupId_fkey',
          columns: ['groupId'],
          references: { schema: 'public', table: 'Group', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'GroupMember',
        foreignKey: {
          name: 'GroupMember_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'InviteCode',
        foreignKey: {
          name: 'InviteCode_createdById_fkey',
          columns: ['createdById'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'restrict',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'InviteCode',
        foreignKey: {
          name: 'InviteCode_groupId_fkey',
          columns: ['groupId'],
          references: { schema: 'public', table: 'Group', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Notification',
        foreignKey: {
          name: 'Notification_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'PushSubscription',
        foreignKey: {
          name: 'PushSubscription_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'RecurringExpense',
        foreignKey: {
          name: 'RecurringExpense_categoryId_fkey',
          columns: ['categoryId'],
          references: { schema: 'public', table: 'Category', columns: ['id'] },
          onDelete: 'setNull',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'RecurringExpense',
        foreignKey: {
          name: 'RecurringExpense_createdById_fkey',
          columns: ['createdById'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'restrict',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'RecurringExpense',
        foreignKey: {
          name: 'RecurringExpense_groupId_fkey',
          columns: ['groupId'],
          references: { schema: 'public', table: 'Group', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'RecurringRun',
        foreignKey: {
          name: 'RecurringRun_recurringExpenseId_fkey',
          columns: ['recurringExpenseId'],
          references: { schema: 'public', table: 'RecurringExpense', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Settlement',
        foreignKey: {
          name: 'Settlement_createdById_fkey',
          columns: ['createdById'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'restrict',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Settlement',
        foreignKey: {
          name: 'Settlement_fromUserId_fkey',
          columns: ['fromUserId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'restrict',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Settlement',
        foreignKey: {
          name: 'Settlement_groupId_fkey',
          columns: ['groupId'],
          references: { schema: 'public', table: 'Group', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'Settlement',
        foreignKey: {
          name: 'Settlement_toUserId_fkey',
          columns: ['toUserId'],
          references: { schema: 'public', table: 'User', columns: ['id'] },
          onDelete: 'restrict',
          onUpdate: 'cascade',
        },
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
